/* 
  *   Speech.java generated by speechmod 
 */   

package scxmlgen.Modalities; 

import scxmlgen.interfaces.IModality; 

public enum Speech implements IModality{  

    JOAO("[name][JOAO]",0),
    ANDRE("[name][ANDRE]",0),
    AVEIRO("[city][Aveiro]",0),
    PORTO("[city][Porto]",0),
    NEWS("[subject][NEWS]",0),
    LEAVE("[action][LEAVE]",0),  
    JOIN("[action][JOIN]",0),
    WAKE("[wake][WAKE]",0);

private String event; 
private int timeout;
Speech(String m, int time) {
	event=m;
	timeout=time;
}
@Override
public int getTimeOut(){
	return timeout;
}
@Override
public String getEventName(){
	return event;
}
@Override
public String getEvName(){
	return getModalityName().toLowerCase() +event.toLowerCase();
}

}
