/* 
  *   Speech.java generated by speechmod 
 */   

package scxmlgen.Modalities; 

import scxmlgen.interfaces.IModality; 

public enum Speech implements IModality{  

    JOAO("[name][JOAO]",1500),
    ANDRE("[name][ANDRE]",1500),
    AVEIRO("[name][AVEIRO]",1500),
    PORTO("[name][PORTO]",1500),
    TODOS("[name][TODOS]",1500),
    NEWS("[wake][WAKE][action][TELL][subject][NEWS]",1500),
    LEAVE("[wake][WAKE][action][LEAVE]",1500),  
    JOIN("[wake][WAKE][action][JOIN]",1500),
    WAKE("[wake][WAKE]",1500);

private String event; 
private int timeout;
Speech(String m, int time) {
	event=m;
	timeout=time;
}
@Override
public int getTimeOut(){
	return timeout;
}
@Override
public String getEventName(){
	return event;
}
@Override
public String getEvName(){
	return getModalityName().toLowerCase() +event.toLowerCase();
}

}
